# ВВЕДЕНИЕ {.unnumbered}

Актуальность темы. В современном мире невозможно обойтись без выхода в Интернет: общение, развлечения, образование -- все это можно найти в онлайн-пространстве. Огромное количество людей в качестве инструмента для доступа в сеть выбирают мобильный телефон. В последнее время наблюдается резкий рост использования сервисов по созданию виртуальной частной сети, однако данная технология применяется пользователями бездумно, многие обыватели не задумываются, как такой способ подключения способен навредить их информационной безопасности. Рядовой пользователь может не догадываться о том, что используемый сервис пересылает личную информацию злоумышленнику. На фоне этого имеет место увеличение объемов скомпрометированной информации и утекших данных, это подтверждает статистика компании F6 за 2025 год: 760 млн строк с данными российских пользователей попали в утечки [@f6_leak_2025].

Степень научной разработанности. На сегодняшний день вопросам обнаружения аномалий в сетевом трафике и проектирования систем обнаружения вторжений посвящено большое количество научных работ. Глубоко изучены методы сигнатурного анализа и машинного обучения для выявления подозрительных действий в сети. Вместе с тем большинство существующих решений ориентированы на корпоративный сектор и требуют значительных вычислительных ресурсов и участия квалифицированных специалистов для правильной интерпретации журналов событий.

Проблема исследования. Отсутствие эффективного и удобного для рядового пользователя решения, которое обеспечивало бы комплексную защиту устройств от вредоносной сетевой активности.

***Объектом исследования являются*** системы мониторинга сетевых соединений и защиты пользователей от вредоносной сетевой активности.

***Предметом исследования выступают*** механизмы выявления аномалий в сетевом трафике с использованием поведенческого профилирования.

***Целью выпускной квалификационной работы*** является разработка многоуровневой системы защиты пользователей от вредоносной сетевой активности с использованием поведенческого профилирования.

***Для достижения цели поставлены и решены следующие задачи:***

1)  Проанализировать актуальные векторы сетевых атак;

2)  Провести анализ существующих решений в области систем по обнаружению подозрительной активности в сетевом трафике;

3)  Исследовать алгоритмы машинного обучения для реализации механизма поведенческого профилирования;

4)  Изучить работу анализатора сетевого трафика Zeek;

5)  Спроектировать серверную и клиентскую архитектуру системы;

6) Выполнить программную реализацию спроектированной многоуровневой системы защиты;

7) Провести тестирование разработанной системы и анализ результатов ее работы.

Методы исследования. Анализ существующих решений в области систем по обнаружению подозрительной активности в сетевом трафике, комплексный анализ современных векторов сетевых атак, разработка конвейера обработки данных и пользовательского интерфейса.

Научная новизна. Предложена многоуровневая система защиты, комбинирующая метод поведенческого профилирования со статическим анализом индикаторов компрометации.

Практическая значимость. Результаты работы позволяют внедрить комплексное решение для защиты пользователей, состоящее из серверного анализатора и мобильного приложения. Система автоматически перехватывает трафик, выявляет подозрительную активность, оповещает пользователя о потенциально нежелательном трафике через мобильное приложение.

Структура работы. Пояснительная записка состоит из введения, исследовательского раздела, технологического раздела, заключения, списка использованных источников и приложений. В исследовательском разделе рассматриваются теоретические основы построения системы защиты от вредоносной сетевой активности с использованием поведенческого профилирования: анализ актуальных векторов сетевых атак и решений по защите пользователей от подозрительной сетевой активности, традиционные подходы к выявлению подозрительной активности в сетевом трафике, применение алгоритмов машинного обучения для поиска аномалий в сетевом трафике, централизованный сбор и извлечение признаков сетевого трафика, взаимодействие с пользователем. В специальном разделе выполняется разработка архитектуры многоуровневой системы защиты пользователей от вредоносной сетевой активности с использованием поведенческого профилирования. В технологическом разделе будет представлена практическая реализация системы, описание программной структуры, настройка компонентов и результаты тестирования.